name: llocz
description: Comparte tus lugares.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  cloud_firestore: ^3.5.1
  firebase_core: ^1.24.0
  intl: ^0.17.0
  firebase_auth: ^3.11.2
  email_validator: '^2.1.16'
  file_picker: ^4.5.1
  firebase_storage: ^10.3.11
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.11
  url_launcher: ^6.1.6
  cached_network_image: ^3.2.3
  device_preview: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"
  flutter_native_splash: ^2.2.12

flutter_native_splash:
  color: "#ffffff"
  image: assets/img/app_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/img/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48


flutter:

  uses-material-design: true

  assets:
    - assets/img/app_logo_sin_fondo.png
    - assets/img/app_logo_sin_fondo_negro.png
    - assets/img/app_logo.png
    - assets/img/linkedin.png
    - assets/img/github.png

  fonts:
    - family: MVBoli
      fonts:
      - asset: assets/fonts/mvboli.ttf 
        weight: 400
 
